name: Test Python Script

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # گرفتن کد از ریپازیتوری
      - name: Checkout repository
        uses: actions/checkout@v4

      # نصب پایتون
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # اجرای اسکریپت
      - name: Run script
        run: python long_short_script.py
