name: Run News Script

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests beautifulsoup4

      - name: Run script
        env:
          API_KEY_DEEPSEEK: ${{ secrets.API_KEY_DEEPSEEK }}
        run: python news.py
